# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='my_job',
            field=models.CharField(default='no', max_length=255),
            preserve_default=False,
        ),
    ]
