# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_job_my_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='my_job',
        ),
        migrations.AddField(
            model_name='job',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_jobs', to='dashboard.User'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_jobs', to='dashboard.User'),
        ),
    ]
